"""
PDF Generator for RuralCareAI.

Renders the consultation outcome (prediction, SHAP explanation,
retrieved healthcare knowledge and AI clinical summary) as a
letterhead-style clinical report, rather than a bare text dump.

Author: Sarwajit Kumar Mishra
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# ---------------------------------------------------------------------
# Hindi (Devanagari) font.
#
# ReportLab's built-in fonts (Helvetica etc.) cannot render Devanagari
# script - unsupported glyphs come out as black boxes. Nirmala.ttc
# ships with Windows (8+) and covers Devanagari; if it isn't present
# (e.g. a non-Windows deployment), HINDI_FONT is left as the default
# Helvetica and the Hindi disease-name line is simply omitted rather
# than rendering as boxes.
# ---------------------------------------------------------------------

HINDI_FONT = "Helvetica"

_NIRMALA_PATH = Path(r"C:\Windows\Fonts\Nirmala.ttc")

if _NIRMALA_PATH.exists():
    try:
        pdfmetrics.registerFont(
            TTFont("Nirmala", str(_NIRMALA_PATH), subfontIndex=0)
        )
        HINDI_FONT = "Nirmala"
    except Exception:
        HINDI_FONT = "Helvetica"

# ---------------------------------------------------------------------
# Palette (matches the dissertation viva deck for a consistent look
# across every RuralCareAI deliverable).
# ---------------------------------------------------------------------

NAVY = colors.HexColor("#1B2A6B")
GREEN = colors.HexColor("#2E7D32")
GREEN_LIGHT = colors.HexColor("#EAF7EA")
TEAL = colors.HexColor("#00796B")
TEAL_LIGHT = colors.HexColor("#E0F2F1")
ORANGE = colors.HexColor("#E67E22")
GOLD = colors.HexColor("#B8860B")
GOLD_LIGHT = colors.HexColor("#FFF8E1")
RED = colors.HexColor("#C62828")
RED_LIGHT = colors.HexColor("#FDECEA")
GRAY = colors.HexColor("#5A5A6E")
LIGHT_GRAY = colors.HexColor("#F4F4F7")
BORDER = colors.HexColor("#D9D9E3")

RISK_COLORS = {
    "Critical": (RED, RED_LIGHT),
    "High": (ORANGE, colors.HexColor("#FFF3E0")),
    "Medium": (GOLD, GOLD_LIGHT),
    "Low": (GREEN, GREEN_LIGHT),
}

PAGE_MARGIN = 20 * mm
HEADER_HEIGHT = 24 * mm
FOOTER_TEXT = (
    "This report is generated by an AI-assisted clinical decision-support "
    "tool and does not replace professional medical diagnosis."
)


def _esc(text) -> str:
    """XML-escape a raw value before embedding it in a Paragraph."""
    text = "" if text is None else str(text)
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _humanize(symptom: str) -> str:
    return symptom.replace("_", " ").title()


def _markdown_lite_to_reportlab(text: str) -> list[str]:
    """
    Convert the LLM's lightly-markdown-formatted output into a list of
    ReportLab-safe paragraph strings: escapes XML-special characters,
    converts **bold** into <b>bold</b>, and drops stray separator
    lines (e.g. "***") the model sometimes emits.
    """

    paragraphs = []

    for raw_line in text.split("\n"):
        line = raw_line.strip()

        if not line or set(line) <= {"*", "-", "_"}:
            continue

        line = _esc(line)
        line = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", line)

        paragraphs.append(line)

    return paragraphs


def _styles():
    base = getSampleStyleSheet()

    return {
        "section": ParagraphStyle(
            "Section", parent=base["Heading2"],
            textColor=NAVY, fontSize=13, spaceBefore=14, spaceAfter=6,
        ),
        "subsection": ParagraphStyle(
            "SubSection", parent=base["Heading3"],
            textColor=GRAY, fontSize=10.5, spaceBefore=6, spaceAfter=3,
        ),
        "body": ParagraphStyle(
            "Body", parent=base["Normal"], fontSize=9.5, leading=13.5,
        ),
        "bullet": ParagraphStyle(
            "Bullet", parent=base["Normal"], fontSize=9.5, leading=13.5,
            leftIndent=10, bulletIndent=0,
        ),
        "muted": ParagraphStyle(
            "Muted", parent=base["Normal"], fontSize=8, textColor=GRAY,
        ),
        "disease_name": ParagraphStyle(
            "DiseaseName", parent=base["Normal"], fontSize=17, leading=20,
            fontName="Helvetica-Bold",
        ),
        "disease_hindi": ParagraphStyle(
            "DiseaseHindi", parent=base["Normal"], fontSize=10.5,
            textColor=GRAY, spaceAfter=4, fontName=HINDI_FONT,
        ),
        "recommendation": ParagraphStyle(
            "Recommendation", parent=base["Normal"], fontSize=9.5, leading=13,
        ),
        "metric_label": ParagraphStyle(
            "MetricLabel", parent=base["Normal"], fontSize=8,
            textColor=GRAY, alignment=TA_RIGHT,
        ),
        "metric_value": ParagraphStyle(
            "MetricValue", parent=base["Normal"], fontSize=13,
            fontName="Helvetica-Bold", alignment=TA_RIGHT,
        ),
    }


def _section_rule(width, color=BORDER):
    t = Table([[""]], colWidths=[width], rowHeights=[0.6])
    t.setStyle(TableStyle([("LINEBELOW", (0, 0), (-1, -1), 0.75, color)]))
    return t


def _bulleted(items, style):
    return [Paragraph(f"&bull;&nbsp;&nbsp;{_esc(i)}", style) for i in items]


class PDFGenerator:

    @staticmethod
    def generate_consultation_report(
        filename,
        patient,
        prediction,
        symptoms,
        doctor_notes,
        explanation=None,
        knowledge=None,
        ai_summary=None,
    ):
        styles = _styles()
        content_width = A4[0] - 2 * PAGE_MARGIN

        generated_at = datetime.now().strftime("%d-%b-%Y %H:%M")

        risk_level = prediction.get("risk_level", "Low")
        risk_color, risk_bg = RISK_COLORS.get(risk_level, (GRAY, LIGHT_GRAY))

        story = []

        # ---------------------------------------------------------
        # Patient Details
        # ---------------------------------------------------------

        story.append(Paragraph("Patient Details", styles["section"]))
        story.append(_section_rule(content_width))
        story.append(Spacer(1, 6))

        patient_rows = [
            ["Patient ID", _esc(patient.patient_code), "Date", generated_at],
            [
                "Name", _esc(patient.full_name),
                "Age / Gender", f"{patient.age} / {_esc(patient.gender)}",
            ],
            [
                "Village", _esc(patient.village) or "N/A",
                "District", _esc(getattr(patient, "district", None)) or "N/A",
            ],
            [
                "Mobile", _esc(getattr(patient, "mobile_number", None)) or "N/A",
                "Blood Group", _esc(getattr(patient, "blood_group", None)) or "N/A",
            ],
        ]

        patient_table = Table(
            patient_rows,
            colWidths=[28 * mm, content_width / 2 - 28 * mm,
                       28 * mm, content_width / 2 - 28 * mm],
        )
        patient_table.setStyle(TableStyle([
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("TEXTCOLOR", (0, 0), (0, -1), GRAY),
            ("TEXTCOLOR", (2, 0), (2, -1), GRAY),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LINEBELOW", (0, 0), (-1, -2), 0.4, BORDER),
        ]))

        story.append(patient_table)
        story.append(Spacer(1, 14))

        # ---------------------------------------------------------
        # Diagnosis Card
        # ---------------------------------------------------------

        hindi_name = (knowledge or {}).get("hindi")

        left_cell = [
            Paragraph(_esc(prediction["predicted_disease"]), styles["disease_name"]),
        ]

        if hindi_name and HINDI_FONT != "Helvetica":
            left_cell.append(Paragraph(_esc(hindi_name), styles["disease_hindi"]))

        left_cell.append(Spacer(1, 4))
        left_cell.append(
            Paragraph(_esc(prediction.get("recommendation", "")), styles["recommendation"])
        )

        right_cell = [
            Paragraph("CONFIDENCE", styles["metric_label"]),
            Paragraph(f"{prediction['confidence']:.1f}%", styles["metric_value"]),
            Spacer(1, 6),
            Paragraph("RISK LEVEL", styles["metric_label"]),
            Paragraph(
                f'<font color="{risk_color.hexval()}">{risk_level.upper()}</font>',
                styles["metric_value"],
            ),
        ]

        diagnosis_table = Table(
            [[left_cell, right_cell]],
            colWidths=[content_width * 0.68, content_width * 0.32],
        )
        diagnosis_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), risk_bg),
            ("BOX", (0, 0), (-1, -1), 1.2, risk_color),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (0, 0), 14),
            ("RIGHTPADDING", (1, 0), (1, 0), 14),
            ("TOPPADDING", (0, 0), (-1, -1), 12),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
        ]))

        story.append(diagnosis_table)
        story.append(Spacer(1, 14))

        # ---------------------------------------------------------
        # Symptoms
        # ---------------------------------------------------------

        story.append(Paragraph("Reported Symptoms", styles["section"]))
        story.append(_section_rule(content_width))
        story.append(Spacer(1, 4))

        symptom_text = "&nbsp;&nbsp;&bull;&nbsp;&nbsp;".join(
            _esc(_humanize(s)) for s in symptoms
        )
        story.append(Paragraph(symptom_text, styles["body"]))
        story.append(Spacer(1, 12))

        # ---------------------------------------------------------
        # SHAP Explanation
        # ---------------------------------------------------------

        if explanation:

            story.append(Paragraph("Why did the AI predict this? (SHAP)", styles["section"]))
            story.append(_section_rule(content_width))
            story.append(Spacer(1, 4))
            story.append(Paragraph(
                "Contribution of each reported symptom toward the "
                "symptom-based (text/voice) model's own prediction - "
                "not the uploaded image, if any. Positive values push "
                "toward that model's predicted disease; negative values "
                "push away from it.",
                styles["muted"],
            ))
            story.append(Spacer(1, 6))

            shap_rows = [["Symptom", "SHAP Value", "Impact"]]

            for row in explanation:
                value = row["Importance"]
                impact = "Increases risk" if value >= 0 else "Decreases risk"
                shap_rows.append([
                    _humanize(row["Symptom"]),
                    f"{value:+.4f}",
                    impact,
                ])

            shap_table = Table(
                shap_rows,
                colWidths=[content_width * 0.4, content_width * 0.25, content_width * 0.35],
            )

            shap_style = [
                ("BACKGROUND", (0, 0), (-1, 0), NAVY),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("LINEBELOW", (0, 0), (-1, -2), 0.4, BORDER),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GRAY]),
            ]

            for i, row in enumerate(explanation, start=1):
                color = GREEN if row["Importance"] >= 0 else RED
                shap_style.append(("TEXTCOLOR", (1, i), (2, i), color))

            shap_table.setStyle(TableStyle(shap_style))

            story.append(shap_table)
            story.append(Spacer(1, 12))

        # ---------------------------------------------------------
        # Knowledge Base (RAG)
        # ---------------------------------------------------------

        if knowledge:

            story.append(Paragraph("Disease Information", styles["section"]))
            story.append(_section_rule(content_width))
            story.append(Spacer(1, 4))

            story.append(Paragraph(_esc(knowledge.get("description", "N/A")), styles["body"]))
            story.append(Spacer(1, 8))

            if knowledge.get("precautions"):
                story.append(Paragraph("Precautions", styles["subsection"]))
                story.extend(_bulleted(knowledge["precautions"], styles["bullet"]))
                story.append(Spacer(1, 6))

            if knowledge.get("first_aid"):
                story.append(Paragraph("First Aid", styles["subsection"]))
                story.extend(_bulleted(knowledge["first_aid"], styles["bullet"]))
                story.append(Spacer(1, 6))

            if knowledge.get("when_to_consult"):
                story.append(Paragraph("When to Consult a Doctor", styles["subsection"]))
                story.append(Paragraph(_esc(knowledge["when_to_consult"]), styles["body"]))
                story.append(Spacer(1, 8))

            if knowledge.get("emergency_signs"):

                warning_body = [
                    Paragraph(
                        '<font color="#C62828"><b>EMERGENCY WARNING SIGNS</b></font>',
                        styles["body"],
                    ),
                    Spacer(1, 3),
                ] + _bulleted(knowledge["emergency_signs"], styles["bullet"])

                warning_table = Table([[warning_body]], colWidths=[content_width])
                warning_table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, -1), RED_LIGHT),
                    ("BOX", (0, 0), (-1, -1), 1, RED),
                    ("LEFTPADDING", (0, 0), (-1, -1), 10),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                    ("TOPPADDING", (0, 0), (-1, -1), 8),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ]))

                story.append(warning_table)

            story.append(Spacer(1, 12))

        # ---------------------------------------------------------
        # AI Clinical Summary (Local LLM)
        # ---------------------------------------------------------

        if ai_summary:

            story.append(Paragraph("AI Clinical Summary", styles["section"]))
            story.append(_section_rule(content_width))
            story.append(Spacer(1, 4))
            story.append(Paragraph(
                "Generated locally by Gemma 3 via Ollama, grounded in the disease "
                "information above.",
                styles["muted"],
            ))
            story.append(Spacer(1, 6))

            summary_body = [
                Paragraph(line, styles["body"])
                for line in _markdown_lite_to_reportlab(ai_summary)
            ]

            summary_table = Table([[summary_body]], colWidths=[content_width])
            summary_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), TEAL_LIGHT),
                ("BOX", (0, 0), (-1, -1), 0.75, TEAL),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ]))

            story.append(summary_table)
            story.append(Spacer(1, 12))

        # ---------------------------------------------------------
        # Doctor Notes
        # ---------------------------------------------------------

        if doctor_notes and doctor_notes.strip():

            story.append(Paragraph("Doctor Notes", styles["section"]))
            story.append(_section_rule(content_width))
            story.append(Spacer(1, 4))
            story.append(Paragraph(_esc(doctor_notes), styles["body"]))

        # ---------------------------------------------------------
        # Build
        # ---------------------------------------------------------

        def _header_footer(canvas_obj, doc):
            canvas_obj.saveState()
            width, height = A4

            canvas_obj.setFillColor(NAVY)
            canvas_obj.rect(0, height - HEADER_HEIGHT, width, HEADER_HEIGHT, fill=1, stroke=0)

            canvas_obj.setFillColor(colors.white)
            canvas_obj.setFont("Helvetica-Bold", 18)
            canvas_obj.drawString(PAGE_MARGIN, height - 14 * mm, "RuralCare AI")

            canvas_obj.setFont("Helvetica", 8.5)
            canvas_obj.drawString(
                PAGE_MARGIN, height - 19 * mm,
                "AI-Based Rural Healthcare Triage Assistant",
            )

            canvas_obj.setFont("Helvetica-Bold", 9)
            canvas_obj.drawRightString(
                width - PAGE_MARGIN, height - 14 * mm,
                "CLINICAL CONSULTATION REPORT",
            )

            canvas_obj.setFont("Helvetica", 8)
            canvas_obj.drawRightString(
                width - PAGE_MARGIN, height - 19 * mm,
                f"Generated: {generated_at}",
            )

            canvas_obj.setStrokeColor(BORDER)
            canvas_obj.setLineWidth(0.5)
            canvas_obj.line(PAGE_MARGIN, 16 * mm, width - PAGE_MARGIN, 16 * mm)

            canvas_obj.setFillColor(GRAY)
            canvas_obj.setFont("Helvetica", 7)
            canvas_obj.drawString(PAGE_MARGIN, 11 * mm, FOOTER_TEXT)
            canvas_obj.drawRightString(
                width - PAGE_MARGIN, 11 * mm,
                f"Page {canvas_obj.getPageNumber()}",
            )

            canvas_obj.restoreState()

        pdf = SimpleDocTemplate(
            filename,
            pagesize=A4,
            topMargin=HEADER_HEIGHT + 8 * mm,
            bottomMargin=20 * mm,
            leftMargin=PAGE_MARGIN,
            rightMargin=PAGE_MARGIN,
            title="RuralCareAI Consultation Report",
        )

        pdf.build(
            story,
            onFirstPage=_header_footer,
            onLaterPages=_header_footer,
        )
